/**
 * `InsightDrawer` — the non-modal AI Insights side drawer (UX §4, §5; visual
 * spec §3). It is the single app-level surface that presents a generated
 * insight: a right-side rail on desktop and a bottom sheet on mobile that the
 * user can read while still seeing (and tabbing back to) their data — hence
 * NON-modal, no focus trap (UX §4.1, §8.1; HAX G11 "see why").
 *
 * It consumes {@link useAiInsight} and renders the six UX §5 states:
 *
 *  - **idle** — scope, a primary Generate/Explain action, and the safe
 *    suggested-question chips (UX §7.6), each mapping to `run(input, brief)`.
 *  - **generating** — the streamed narrative token-by-token with a
 *    reduced-motion-aware caret, the coarse status line + WebLLM load progress,
 *    a Stop button, the source panel shown immediately, and the inseparable
 *    caveat from the first token.
 *  - **complete** — the narrative wrapped in {@link InsightCaveat}, the expanded
 *    "show your work" source panel, a `usedFallback` notice, thumbs feedback,
 *    and Regenerate / Copy (copy ALWAYS carries the caveat — never naked prose).
 *  - **error** — the mapped plain-language message + a primary recovery action;
 *    a `needs-consent` error routes the user to Settings → Integrations rather
 *    than rendering a consent dialog here.
 *  - **empty / insufficient-data** — a calm empty state (no model call was made)
 *    plus the source panel showing whatever exists.
 *
 * Accessibility (UX §8): focus moves to the scope `<h2>` on open and returns to
 * the invoking affordance on close; `Esc` closes; the streamed text updates a
 * normal element for sighted users while a SEPARATE coarse `aria-live="polite"`
 * region (flushed at sentence boundaries, not per token) carries intelligible
 * screen-reader announcements (UX §8.3). The ✨/AI label uses {@link AiMarker}.
 *
 * @module components/insights/InsightDrawer
 */

import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { AiMarker, InsightCaveat, MedicalDisclaimer } from '@/components/ai';
import { useAiInsight } from '@/hooks/useAiInsight';
import type { ErrorPrimaryAction, UseAiInsight } from '@/hooks/useAiInsight';
import { useSettingsStore } from '@/stores/useSettingsStore';

import { chipsForInsight } from './chips';
import { SourcePanel } from './SourcePanel';
import { useInsightDrawerStore } from './useInsightDrawerStore';
import styles from './InsightDrawer.module.css';

/** Friendly backend names for the egress reminder + provenance line. */
const BACKEND_LABELS: Record<string, string> = {
  anthropic: 'Claude',
  'openai-compatible': 'your AI endpoint',
  webllm: 'the on-device model',
  'chrome-ai': "Chrome's built-in AI",
};

/** The exact copy footer appended on Copy (UX §7.3) — never naked prose. */
function copyFooter(generatedOnDate: string): string {
  return `— Generated by AI from your CPAP Analyzer data on ${generatedOnDate}. May be inaccurate; verify against your data. Not medical advice.`;
}

/** Coarse status-line text for the generating phase (UX §5.2). */
function phaseLabel(phase: UseAiInsight['phase']): string {
  switch (phase) {
    case 'loading':
      return 'Loading model…';
    case 'generating':
      return 'Generating…';
    case 'preparing':
    default:
      return 'Preparing your numbers…';
  }
}

/** Map an error's primary action to its button label (UX §6). */
function actionLabel(action: ErrorPrimaryAction): string {
  switch (action) {
    case 'open-settings':
    case 'open-settings-key':
      return 'Finish setup in Settings';
    case 'switch-on-device':
      return 'Retry';
    case 'download-model':
      return 'Open AI Insights settings';
    case 'pick-smaller-model':
      return 'Open AI Insights settings';
    case 'retry':
    case 'regenerate':
    default:
      return 'Try again';
  }
}

/**
 * The AI Insights drawer. Mounted once at the app shell; it renders nothing
 * unless the drawer store is open. `insightHook` is injectable for tests so the
 * state machine can be driven without a real provider.
 */
export function InsightDrawer({
  insightHook = useAiInsight,
}: {
  /** Injected hook (defaults to {@link useAiInsight}); overridden in tests. */
  readonly insightHook?: typeof useAiInsight;
} = {}) {
  const open = useInsightDrawerStore((s) => s.open);
  const request = useInsightDrawerStore((s) => s.request);
  const close = useInsightDrawerStore((s) => s.close);

  if (!open || request === null) return null;
  return (
    <InsightDrawerBody
      key={JSON.stringify(request.input.kind) + request.scopeLabel}
      insightHook={insightHook}
      onClose={close}
    />
  );
}

/**
 * The drawer body — split out so the hook (and its per-request state) is created
 * fresh each time a new request opens the drawer (via the `key` above), giving a
 * clean idle state per insight.
 */
function InsightDrawerBody({
  insightHook,
  onClose,
}: {
  readonly insightHook: typeof useAiInsight;
  readonly onClose: () => void;
}) {
  const request = useInsightDrawerStore((s) => s.request);
  const navigate = useNavigate();
  const backend = useSettingsStore((s) => s.integrations.llm.backend);
  const anthropicModel = useSettingsStore((s) => s.integrations.llm.anthropic.model);

  const insight = insightHook();
  const {
    state,
    text,
    error,
    sourceContext,
    usedFallback,
    progress,
    phase,
    emptyReason,
    feedback,
    needsConsent,
    isGenerating,
    run,
    stop,
    regenerate,
    setFeedback,
  } = insight;

  const headingRef = useRef<HTMLHeadingElement>(null);
  const triggerToRestore = useRef<HTMLElement | null>(null);
  const [copied, setCopied] = useState(false);

  // Remember the element that had focus when the drawer opened, and move focus
  // to the scope heading (UX §8.2). Restore focus to the trigger on unmount.
  useEffect(() => {
    triggerToRestore.current =
      document.activeElement instanceof HTMLElement ? document.activeElement : null;
    headingRef.current?.focus();
    return () => {
      triggerToRestore.current?.focus();
    };
  }, []);

  // Esc closes the drawer (UX §8.1). Non-modal, so this is a document listener
  // rather than a dialog's built-in trap.
  useEffect(() => {
    const onKey = (e: KeyboardEvent): void => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [onClose]);

  if (request === null) return null;

  const isCloud = backend === 'anthropic' || backend === 'openai-compatible';
  const backendLabel = (backend && BACKEND_LABELS[backend]) ?? 'AI Insights';

  const startRun = (brief?: string): void => {
    setCopied(false);
    run(request.input, brief);
  };

  const handleCopy = (): void => {
    // Copy ALWAYS carries the caveat footer — never naked prose (UX §7.3, §9.3).
    const generatedOnDate = sourceContext?.generatedOnDate ?? '';
    const payload = `${text}\n\n${copyFooter(generatedOnDate)}`;
    void navigator.clipboard?.writeText(payload).then(
      () => setCopied(true),
      () => setCopied(false),
    );
  };

  const handlePrimaryErrorAction = (): void => {
    if (error === null) return;
    switch (error.primaryAction) {
      case 'open-settings':
      case 'open-settings-key':
      case 'download-model':
      case 'pick-smaller-model':
        navigate('/settings');
        break;
      case 'retry':
      case 'regenerate':
      case 'switch-on-device':
      default:
        regenerate();
        break;
    }
  };

  const chips = chipsForInsight(request.input);

  return (
    <aside
      className={styles.drawer}
      role="complementary"
      aria-label="AI insight"
      aria-busy={isGenerating}
    >
      <div className={styles.scroll}>
        {/* ── Header ─────────────────────────────────────────────────────── */}
        <div className={styles.header}>
          <div className={styles.headerText}>
            <div className={styles.headerTitleRow}>
              <h2 className={styles.title} tabIndex={-1} ref={headingRef}>
                AI summary
              </h2>
              <AiMarker variant="pill" />
            </div>
            <span className={styles.scope}>Summary of {request.scopeLabel}</span>
          </div>
          <button
            type="button"
            className={styles.closeButton}
            onClick={onClose}
            aria-label="Close AI insight"
          >
            <span aria-hidden="true">×</span>
          </button>
        </div>

        {/* ── Per-output egress reminder (cloud backends only) ───────────── */}
        {isCloud && (
          <p className={styles.egressReminder}>
            Sends a metric snapshot to {backendLabel}. No raw data leaves your device.
          </p>
        )}

        {/* ── Idle ───────────────────────────────────────────────────────── */}
        {state === 'idle' && (
          <>
            <button
              type="button"
              className={`${styles.actionButton} ${styles.primaryAction}`}
              onClick={() => startRun()}
            >
              Generate summary
            </button>
            <div className={styles.chips} role="group" aria-label="Suggested questions">
              {chips.map((chip) => (
                <button
                  key={chip.id}
                  type="button"
                  className={styles.chip}
                  onClick={() => startRun(chip.brief)}
                >
                  <span className={styles.chipGlyph} aria-hidden="true">
                    ✨
                  </span>
                  {chip.label}
                </button>
              ))}
            </div>
          </>
        )}

        {/* ── Generating (streaming) ─────────────────────────────────────── */}
        {state === 'generating' && (
          <>
            <p className={styles.statusLine}>
              <span>{phaseLabel(phase)}</span>
              {progress !== null && progress.fraction !== null && (
                <span className={styles.progress}>{Math.round(progress.fraction * 100)}%</span>
              )}
            </p>
            <p className={styles.prose}>
              {text}
              <span className={styles.caret} aria-hidden="true">
                ▍
              </span>
            </p>
            <InsightCaveat />
            <SourcePanel context={sourceContext} />
            <button type="button" className={styles.actionButton} onClick={stop}>
              Stop
            </button>
          </>
        )}

        {/* ── Complete ───────────────────────────────────────────────────── */}
        {state === 'complete' && (
          <>
            {usedFallback && (
              <p className={styles.fallbackNotice}>
                The AI wording could not be verified against your numbers, so a plain template
                summary is shown instead.
              </p>
            )}
            <p className={styles.prose}>{text}</p>
            <InsightCaveat />
            <SourcePanel context={sourceContext} />

            <div className={styles.actionRow}>
              <button type="button" className={styles.actionButton} onClick={() => regenerate()}>
                <span aria-hidden="true">↻</span> Regenerate
              </button>
              <button type="button" className={styles.actionButton} onClick={handleCopy}>
                {copied ? 'Copied' : 'Copy'}
              </button>
              <button
                type="button"
                className={`${styles.actionButton} ${feedback === 'up' ? styles.actionButtonActive : ''}`}
                aria-pressed={feedback === 'up'}
                aria-label="Mark this summary helpful (saved on your device only)"
                title="Saved on your device only"
                onClick={() => setFeedback(feedback === 'up' ? null : 'up')}
              >
                <span aria-hidden="true">👍</span>
              </button>
              <button
                type="button"
                className={`${styles.actionButton} ${feedback === 'down' ? styles.actionButtonActive : ''}`}
                aria-pressed={feedback === 'down'}
                aria-label="Mark this summary not helpful (saved on your device only)"
                title="Saved on your device only"
                onClick={() => setFeedback(feedback === 'down' ? null : 'down')}
              >
                <span aria-hidden="true">👎</span>
              </button>
            </div>

            <p className={styles.provenance}>
              {backendLabel}
              {backend === 'anthropic' ? ` · ${anthropicModel}` : ''}
              {sourceContext ? ` · ${sourceContext.generatedOnDate}` : ''}
            </p>
            <MedicalDisclaimer />
          </>
        )}

        {/* ── Error ──────────────────────────────────────────────────────── */}
        {state === 'error' && error !== null && (
          <div className={styles.error} role="alert">
            <p className={styles.errorTitle}>
              {needsConsent !== null ? 'Finish AI Insights setup' : 'AI Insights couldn’t run'}
            </p>
            <p className={styles.errorMessage}>
              {needsConsent !== null
                ? `Using ${backendLabel} sends a metric snapshot online, which needs your consent. Finish setup in Settings to continue.`
                : error.message}
            </p>
            <button
              type="button"
              className={`${styles.actionButton} ${styles.primaryAction}`}
              onClick={handlePrimaryErrorAction}
            >
              {needsConsent !== null
                ? 'Finish setup in Settings'
                : actionLabel(error.primaryAction)}
            </button>
            {/* The source numbers stay visible even on error (HAX G11). */}
            <SourcePanel context={sourceContext} />
          </div>
        )}

        {/* ── Empty / insufficient data ──────────────────────────────────── */}
        {state === 'empty' && (
          <>
            <div className={styles.empty}>
              <span className={styles.emptyIcon} aria-hidden="true">
                ◔
              </span>
              <p className={styles.emptyMessage}>
                {emptyReason === 'too-few-for-trend'
                  ? 'A trend needs at least a few nights. Widen the range to see a trend summary.'
                  : emptyReason === 'metric-unavailable'
                    ? 'This view doesn’t include the data needed to explain it here.'
                    : 'There’s no data in this range to summarize. Pick a range that includes nights with data, or import more sessions.'}
              </p>
            </div>
            <SourcePanel context={sourceContext} emptyReason={emptyReason} />
          </>
        )}

        {/* ── Coarse live region for screen readers (UX §8.3) ────────────── */}
        <StreamingAnnouncer
          text={state === 'generating' ? text : ''}
          complete={state === 'complete'}
        />
      </div>
    </aside>
  );
}

/**
 * A SEPARATE, visually-hidden `aria-live="polite"` region that announces
 * streamed prose to screen readers at coarse intervals — at sentence boundaries
 * — rather than per token (which would be a "token storm"; UX §8.3). On
 * completion it announces a terminal cue.
 */
function StreamingAnnouncer({
  text,
  complete,
}: {
  readonly text: string;
  readonly complete: boolean;
}) {
  const [announced, setAnnounced] = useState('');
  const lastFlushedLength = useRef(0);

  useEffect(() => {
    if (text === '') {
      lastFlushedLength.current = 0;
      return;
    }
    // Flush only completed sentences since the last flush (coarse, intelligible).
    const lastSentenceEnd = Math.max(
      text.lastIndexOf('. '),
      text.lastIndexOf('! '),
      text.lastIndexOf('? '),
    );
    if (lastSentenceEnd > lastFlushedLength.current) {
      setAnnounced(text.slice(0, lastSentenceEnd + 1));
      lastFlushedLength.current = lastSentenceEnd + 1;
    }
  }, [text]);

  return (
    <div className={styles.visuallyHidden} aria-live="polite" aria-atomic="false">
      {complete ? 'Summary complete.' : announced}
    </div>
  );
}
